version: "3"
services:

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - mern-network
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80

  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern-network
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
    depends_on:
      - backend
    environment:
      - REACT_APP_SERVER=http://localhost:4000
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mern-network
    volumes:
      - ./backend:/usr/app/src
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017
      - CLIENT=http://localhost:3000
    command: npm start

  db:
    image: mongo:5.0.5
    ports:
      - 27017:27017
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

  

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
